<?php
/* This file is part of Springfiles (GPL v2 or later), see LICENSE.txt */

/**
 * @author abma <spam@abma.de>
 * @file
 * module file for dlc drupal module, registers hooks
 */

require_once ( dirname(__FILE__) . '/includes/dlc.cron.inc');
require_once ( dirname(__FILE__) . '/includes/dlc.output.inc');

/**
 * Implementation of hook_help().
 */
function dlc_help($path, $arg) {
  switch ($path) {
    case 'admin/help#dlc':
    return '<p>'. t("displays and aggregates file downloads data for files stored in the drupal files table") .'</p>';
  }
}

/**
 * Implementation of hook_perm().
 */
function dlc_perm() {
  $perms = array('view all download counts', 'view own download counts');
  return $perms;
}

/**
 * Implementation of hook_cron().
 */

function dlc_cron() {
	dlc_cron_run();
}
/**
 * Generates some testdata
 */

function dlc_testdata(){
	$timestamp=time();
	for($i=0;$i<500000; $i++){
		$timestamp= $timestamp - 861;
		db_query("INSERT INTO download_count (fid, nid, uid, vid, ip_address, referrer, mirror, timestamp) VALUES
			(".intval($i/1000).", 0, 0, 0, \"1.1.1.1\", \"\",  0, $timestamp)"); 
	}
	return "";
}
/*
 * registers the urls of this module
 */

function dlc_menu(){
	$items=array();
	$items['dlc'] = array(
		'title' => 'dlc', 
		'description' => 'Listing of download counts.', 
		'page callback' => 'dlc_display', 
	   'access arguments' => array('access content'), 
		'type' => MENU_SUGGESTED_ITEM,
  	);
/*
	$items['dlc/testdata'] = array(
		'title' => 'dlc', 
		'description' => 'Listing of download counts.', 
		'page callback' => 'dlc_testdata', 
	   'access arguments' => array('access content'), 
		'type' => MENU_SUGGESTED_ITEM,
  	);
*/
  	
  	return $items;
}
